name: 🧪Clazy checks

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get deps
        run: |
          sudo apt-get install \
            cmake \
            ninja-build \
            clang \
            qtbase5-dev \
            qt5keychain-dev \
            qtscript5-dev \
            qtwebengine5-dev

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -GNinja \
          -Do2_BUILD_EXAMPLES:BOOL=ON \
          -Do2_WITH_TESTS=ON \
          -Do2_SHOW_TRACE:BOOL=ON \
          -Do2_WITH_DROPBOX:BOOL=ON \
          -Do2_WITH_FACEBOOK:BOOL=ON \
          -Do2_WITH_FLICKR:BOOL=ON \
          -Do2_WITH_GOOGLE:BOOL=ON \
          -Do2_WITH_HUBIC:BOOL=ON \
          -Do2_WITH_KEYCHAIN:BOOL=ON \
          -Do2_WITH_MSGRAPH:BOOL=ON \
          -Do2_WITH_OAUTH1:BOOL=ON \
          -Do2_WITH_QT5:BOOL=ON \
          -Do2_WITH_SKYDRIVE:BOOL=ON \
          -Do2_WITH_SMUGMUG:BOOL=ON \
          -Do2_WITH_SPOTIFY:BOOL=ON \
          -Do2_WITH_SURVEYMONKEY:BOOL=ON \
          -Do2_WITH_TWITTER:BOOL=ON \
          -Do2_WITH_UBER:BOOL=ON \
          -Do2_WITH_VIMEO:BOOL=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          ..
          ninja
          cd ..

      - name: Clazy action
        id: clazy
        uses: ./.github/actions/clazy
        with:
          checks: 'level0,level1,old-style-connect,no-overloaded-signal'
          install-stable: true
          database: build

      - name: Check Results
        run: |
          # Read directly from GITHUB_OUTPUT
          WARNINGS=$(grep "^warnings-count=" $GITHUB_OUTPUT | cut -d'=' -f2)
          ERRORS=$(grep "^errors-count=" $GITHUB_OUTPUT | cut -d'=' -f2)
          echo "Direct read - Warnings: $WARNINGS, Errors: $ERRORS"

          if [ "$WARNINGS" -gt "0" ] || [ "$ERRORS" -gt "0" ]; then
            echo "Found $WARNINGS warnings and $ERRORS errors"
            exit 1
          fi

      - name: Dump results
        run: |
          echo "Warnings count: ${{ steps.clazy.outputs.warnings-count }}"
          echo "Errors count: ${{ steps.clazy.outputs.errors-count }}"

      - name: Fail if warnings or errors exist
        if: ${{ fromJSON(steps.clazy.outputs.warnings-count) > 0 || fromJSON(steps.clazy.outputs.errors-count) > 0 }}
        run: exit 1
