name: 🧪Clazy checks

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get deps
        run: |
          sudo apt-get install \
            cmake \
            ninja-build \
            clang \
            qtbase5-dev \
            qt5keychain-dev \
            qtscript5-dev \
            qtwebengine5-dev

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -GNinja \
          -Do2_BUILD_EXAMPLES:BOOL=ON \
          -Do2_WITH_TESTS=ON \
          -Do2_SHOW_TRACE:BOOL=ON \
          -Do2_WITH_DROPBOX:BOOL=ON \
          -Do2_WITH_FACEBOOK:BOOL=ON \
          -Do2_WITH_FLICKR:BOOL=ON \
          -Do2_WITH_GOOGLE:BOOL=ON \
          -Do2_WITH_HUBIC:BOOL=ON \
          -Do2_WITH_KEYCHAIN:BOOL=ON \
          -Do2_WITH_MSGRAPH:BOOL=ON \
          -Do2_WITH_OAUTH1:BOOL=ON \
          -Do2_WITH_QT5:BOOL=ON \
          -Do2_WITH_SKYDRIVE:BOOL=ON \
          -Do2_WITH_SMUGMUG:BOOL=ON \
          -Do2_WITH_SPOTIFY:BOOL=ON \
          -Do2_WITH_SURVEYMONKEY:BOOL=ON \
          -Do2_WITH_TWITTER:BOOL=ON \
          -Do2_WITH_UBER:BOOL=ON \
          -Do2_WITH_VIMEO:BOOL=ON \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          ..
          cd ..

      - name: Clazy action
        uses: MinyazevR/clazy-standalone-action@v0.2.1
        with:
          checks: 'level0,level1,old-style-connect'
          warnings_as_errors: 'level0,level1,old-style-connect'
          install-stable: true
          database: build
